### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by seanamor** [alxnns1/MobHunter#3]
Not an issue, just a request, can you provide models of your entities? I'd love to test a a new concept of painting mobs. I will share all art I come up with, just trying to update all the servers textures to a minimum of 32 bit. I thought I'd start on the Velociprey, it's pretty tough painting over the flat texture files.

**Comment by thebrightspark** [comment]
It's already in the source:
https://github.com/alxnns1/MobHunter/tree/master/src/main/java/com/alxnns1/mobhunter/entity/models

If that doesn't work for you, what format would you need the models in?

**Comment by seanamor** [comment]
If possible could I get json, or even better, a techne (.tce) file?

**Comment by seanamor** [comment]
Either json or techne

**Comment by alxnns1** [comment]
Unfortunately the program I use to model the mobs, called MCAnimator, doesn't allow me to export to .tce files or json model files. It doesn't even export to usable model classes. I write the model classes from the values in the program so the ones in the source are all you'd be able to use.

**Comment by seanamor** [comment]
Do you have the mcanimator project files?

**Comment by alxnns1** [comment]
Some of them, I've kept in case I update the models

**Comment by seanamor** [comment]
Excellent, send me what you are willing to send.

I also wanted to note that it seems like a few of the mobs randomly dont interact with players, for example the velociprey randomly ignores you even if you attack it.

**Comment by thebrightspark** [comment]
Sorry, we've had a short break since this issue was opened (we're back at it again though!). The files weren't in a usable format unfortunately - they were made using some app @alxnns1 has with it's own file types. Unfortunately the best I can offer are the Java model classes in the repository.
