### ISSUE TITLE
Mob Spawning Config

### ISSUE THREAD

**Issue by seanamor** [alxnns1/MobHunter#4]
Id like to request a mob spawning config, a way to limit the amount of mobs spawning, and a way to deny the spawning. I made a new world in 1.8.9 and its 99% mob hunter mobs, and appears to override all other mod mobs.

**Comment by thebrightspark** [comment]
Yes I can easily add this. We didn't bother with a config yet since we're still in early development and we'd just add one once it seemed necessary. I'll see about adding it soon. Is there anything else you'd like to suggest being configurable since I'll be adding it?

**Comment by seanamor** [comment]
I dont have any further requests just yet, just the config, they are basically the only mobs spawning in my world. About every chunk I see a cluster of them.

**Comment by thebrightspark** [comment]
No problem, we're just sorting out the last bits for the next update and the config is in there.

**Comment by seanamor** [comment]
any updates? :D

**Comment by thebrightspark** [comment]
Sorry we've both been a bit busy lately. There'll hopefully be an update within the next week and then I'll update the mod to 1.10.2.

**Comment by thebrightspark** [comment]
Sorry, just found this and realised I didn't close it. The configs were added in the first version in 1.10.2.
