### ISSUE TITLE
Will you ever want to add costume music to the modpack?

### ISSUE THREAD

**Issue by SirRicharalar** [alxnns1/MobHunter#8]
I'm a composer and I think I may be able to make music similar to the game, unless you rip it haha if you are interested, i can make a sample?

**Comment by alxnns1** [comment]
We're not sure about in-game music and ambience but one thing we will definitely need is monster sounds as we don't have any yet

**Comment by SirRicharalar** [comment]
I've never done this, let me give it a go 💃

**Comment by SirRicharalar** [comment]
I can try and rip them for you (never done this), or create them from scratch (create a sound and messing with that sound until it sounds cool. This can be big ambient rawrs or small bug screeches)?

**Comment by alxnns1** [comment]
I was initially gonna use sounds ripped from the game, but I would prefer to avoid copying directly from the games as much as possible

**Comment by SirRicharalar** [comment]
Usually all sounds/music is all copy righted, but I can't find any sourced online to say so. The music most likely is. I'd just rip it if I were you I guess. If the pack does get popular, you may come across Copy right issues then (I can see this going big too).

Do you aim to make this server friendly?

**Comment by alxnns1** [comment]
The mod is server friendly and will remain so as our main testing environment is a server

**Comment by AlexCouch** [comment]
Costume music????

**Comment by thebrightspark** [comment]
Going to close this as it's so old now.
